try {
      throw Error ("Pesan Error ini dibuat menggunakan try...catch");
} catch (e) {
      console.log(e)
}